#!/bin/sh
# Continuously update the graphs
# - weekly: Every 7+ minutes
# - daily: Every 1+ minutes

INTERVAL=61
exclude="--exclude index.html.tmpl --exclude notes --exclude run-cron"

# Do not use linlog axes for Remote Clocks Summary for readability
export FORCE_LINEAR_ALLSTAR=1

./substitute.sh web/*.IN
rsync -au $exclude web/. /web
while true; do
  start=`date +%s`
  (cd week && FREQ=Weekly ../bin/run --plus-svg 7)
  rsync -au $exclude week /web
  now=`date +%s`
  delta=`expr $now - $start`
  echo "=== Updating weekly took ${delta}s; continuing with daily"
  for i in 1 2 3 4 5 6; do
    start=`date +%s`
    (cd day && FREQ=Daily ../bin/run --plus-svg 1)
    rsync -au $exclude day /web
    now=`date +%s`
    delta=`expr $now - $start`
    echo "=== Updating daily took ${delta}s; next in ${INTERVAL}s"
    sleep $INTERVAL
  done
done
